// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var firstLetter, newHtml, rest, title;
    title = $('#creators h1').html();
    console.log(title);
    firstLetter = title.split('')[0];
    newHtml = "<span class='red'>" + firstLetter + "</span>";
    rest = title;
    return $('#creators h1').html(newHtml + title);
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
